### PR TITLE
Change colors for the new buttons.

### PR DESCRIPTION
**Pull request by zero-24**
Implement: 

Include -> Green
Exclude -> Red

@okonomiyaki3000 @roland-d

### CODE REVIEW

**Comment by zero-24** [comment]
but maybe a css fix is better?

PR is: https://github.com/joomla/joomla-cms/pull/5146

**Comment by okonomiyaki3000** [comment]
I'm OK with this except that, until now, there has been a hidden field with value `0` which meant `include` (because there was no exclude option anyway). If `0` will now mean `exclude`, this cause a change to expected behavior. I believe it's a minor thing but I wonder if others may have a different opinion.

**Comment by roland-d** [comment]
We can't do this because it is a backwards compatibility break and what is probably more nagging me is that we have to translate the values for JLog again.

I wasn't aware this was an existing feature and thus changing it would be more hassle than it is worth. The PLT has no issues keeping it as it is now. Let's close this one and merge #5146.

**Comment by zero-24** [comment]
ok closing here. maybe we can add a code comment that we change the values with 4.0? @okonomiyaki3000 @roland-d

**Pull request closed without merging**
